#!/bin/bash
function bule(){
        # '\E[32m' 将打印的信息设置为绿色
                echo -ne "\e[32m$1\e[0m"
        }

/usr/bin/clear

bule 'Internet: '       #测试可以不以联网
ping -c 2 www.baidu.com &>/dev/null  && echo 'connected' || echo 'disconnected' 
# 测试可以不以联网
# &>/dev/null 是指标准输出和错误输出都输出到/dev/null上，而不在界面上显示；

# 不需要加中括号
# [ping -c 2 www.baidu.com &>/dev/null ] && echo 'connected' || echo 'disconnected' 

# ping -c 1 www.baidu.com &> /dev/null && echo -e '\E[32m'"Internet: $tecreset Connected" || echo -e '\E[32m'"Internet: $tecreset Disconnected"


bule 'Operating System Type: '
echo "`uname -o`"

bule 'Architecture: '
echo "`uname -i`"

bule 'Kerbel Release: '
echo "`uname -r`"

bule 'Internal IP: '
# 首先我们需要安装这一条ifconfig命令。。。我选用wlo1 因为我的网卡是选择wlo1
# print用于打印出样式
# echo "`ifconfig|grep -A2 'eth0'|grep 't '|awk -F '[ :]+' '{print $4}'`"
echo "`ifconfig|grep -A2 'wlo1'|grep 't '|awk -F '[ :]+' '{print $3}'`"
# echo ifconfig eth0 |grep 'inte addr' |awk '{print $2}' |awk -F ":" '{print $2}'
# echo "ifconfig| grep -A2 'ens33' | grep 't '|awk '{print $2}'"


# bule 'External IP: '
# echo "`curl -s ipecho.net/plain;echo`"
externalip=$(curl -s ipecho.net/plain;echo)
echo -e '\E[32m'"External IP : $tecreset "$externalip

bule 'Name Servers: '
echo "`cat /etc/resolv.conf | grep 'nameserver '|awk '{print $2}'`"

bule 'Logged In users: '
echo
echo "`who`"

bule "Ram Usages: "
echo
echo "`free -h | sed -n '1,2p'`"

bule "Swap Usages: "
echo
echo "`free -h| sed -n '1p'`"
echo "`free -h| sed -n '4p'`"

bule "Disk Usages: "
echo
echo "`df -h | grep 'Filesystem\|/dev/sda*'`"

bule "Load Average: "
echo "`top -bn1 |head -1 |awk -F ',' '{print $1}'|awk '{print $5,$6}'`"





